version: '3.9'

services:
  backend:
    build: ./api
    container_name: qr-backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0

  frontend:
    build: ./front-end-nextjs
    container_name: qr-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
