apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - fastapi_deployment.yml
  - fastapi_service.yml
  - frontend_deployment.yml
  - frontend_service.yml
  - monitoring/prometheus-configmap.yml
  - monitoring/prometheus-rbac.yml
  - monitoring/prometheus-deployment.yml
  - monitoring/prometheus-service.yml
  - monitoring/grafana-deployment.yml
  - monitoring/grafana-service.yml
