name: build publish image to docker to DockerHub
on: 
  [workflow_dispatch]

jobs: 
  publish_images:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4  
    - name: build image
      run: docker build ./api/ -t zennnnnnnnnn/devops-qr-code-api:latest
    - name: push image to DockerHub
      run: |
        docker push zennnnnnnnnn/devops-qr-code-api:latest  

